server:
  port: 8087
spring:
  application:
    name: movie-pay-user-test
  dubbo:
    server: true
    registry: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20887
      accepts: 10     #服务提供方最大可接受连接数，这里限制服务器端接受的连接不能超过10个。这里限制的是reference，最大10个
  datasource:
    url: jdbc:mysql://localhost:3306/movie?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.dubbo.movie.model



